/**
 * Push action entries from backup JSON to Supabase weapons table.
 * Uses the action-entries.json generated by the transform script.
 *
 * Usage: npx tsx scripts/push-action-entries.ts
 */

import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';

// Load env
const envPath = path.resolve(__dirname, '../.env.local');
const envContent = fs.readFileSync(envPath, 'utf-8');
const env: Record<string, string> = {};
for (const line of envContent.split('\n')) {
    const match = line.match(/^([^#=]+)=(.*)$/);
    if (match) env[match[1].trim()] = match[2].trim();
}

const supabaseUrl = env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error('Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY');
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function main() {
    // Read action entries from backup
    const entriesPath = path.resolve(__dirname, '../backups/2026-03-02-pre-actions-unification/action-entries.json');
    const entries = JSON.parse(fs.readFileSync(entriesPath, 'utf-8'));
    console.log(`Loaded ${entries.length} action entries from backup`);

    // Convert to DB row format
    const rows = entries.map((e: Record<string, unknown>) => ({
        id: e.id,
        name: e.name,
        source: e.source ?? 'Custom',
        faction_variants: e.factionVariants,
        is_weapon: e.isWeapon ?? false,
        is_gear: e.isGear ?? false,
        is_action: e.isAction ?? true,
        range_red: e.rangeRed ?? false,
        range_yellow: e.rangeYellow ?? false,
        range_green: e.rangeGreen ?? false,
        range_long: e.rangeLong ?? false,
        description: e.description ?? '',
        keywords: e.keywords ?? [],
        updated_at: new Date().toISOString(),
    }));

    // Batch upsert
    for (let i = 0; i < rows.length; i += 50) {
        const chunk = rows.slice(i, i + 50);
        const { error } = await supabase.from('weapons').upsert(chunk);
        if (error) {
            console.error(`Batch ${Math.floor(i / 50) + 1} failed:`, error.message);
        } else {
            console.log(`Batch ${Math.floor(i / 50) + 1}: ${chunk.length} actions upserted`);
        }
    }

    // Verify
    const { data, error } = await supabase.from('weapons').select('id').eq('is_action', true);
    console.log(`\nTotal actions in DB: ${data?.length ?? 'error'}`);
    if (error) console.error(error.message);
}

main().catch(console.error);
